version: "3.8"

services:
  db:
    container_name: db
    build: ./db
    networks:
      - proxynetwork
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    container_name: backend
    build: ./backend
    env_file: ./backend/.env
    networks:
      - proxynetwork
    depends_on:
      - db
    links:
      - db
  reverseproxy:
    container_name: reverseproxy
    build: ./reverseproxy
    ports:
      - "80:80"
    networks:
      - proxynetwork
    depends_on:
      - backend
    links:
      - backend
networks:
  proxynetwork:
    name: proxynetwork
    driver: bridge
volumes:
  dbdata:
    name: dbdata
