version: '3'
services:
  appweb:
    container_name: appweb
    image: httpd
    expose:
      - 80
    networks:
      - mynet
  db:
    container_name: db
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - mynet
  reverseproxy:
    container_name: reverseproxy
    build: ./nginx-reverse-proxy
    ports:
      - '80:80'
    networks:
      - mynet
    depends_on:
      - appweb
      - db
networks:
  mynet:
    name: mynet
    driver: bridge
