version: "3.8"
services:
  app-database:
    container_name: app-database
    build: ./app-database
    networks:
      - app-network
    volumes:
      - app-database-data:/var/lib/postgresql/data
  app-backend:
    container_name: app-backend
    build: ./app-backend
    env_file: ./app-backend/.env
    networks:
      - app-network
    depends_on:
      - app-database
    links:
      - app-database
  app-reverse-proxy:
    container_name: app-reverse-proxy
    build: ./app-reverse-proxy
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - app-backend
    links:
      - app-backend
networks:
  app-network:
    name: app-network
    driver: bridge
volumes:
  app-database-data:
    name: app-database-data
